server:
  port: 18081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.168:3306/guli_pms
    username: root
    password: 12345
  redis:
    host: 192.168.1.168
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port:8719


  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
    feign:
      enabled: true

  mybatis-plus:
